# Generated by Django 5.2.3 on 2025-06-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('transaction_id', models.UUIDField(unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    'currency',
                    models.CharField(
                        choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')],
                        max_length=3,
                    ),
                ),
                ('customer_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
